USE FISH
GO

ALTER TABLE [Member.Members]
ADD UserName VARCHAR(50);

ALTER TABLE [Member.Members]
ALTER COLUMN [Email] VARCHAR(100) NOT NULL

ALTER TABLE [Member.Members]
ALTER COLUMN [PIN] NVARCHAR(50) NOT NULL

ALTER TABLE [Member.Members]
ALTER COLUMN [PIN] VARCHAR(20) NOT NULL

ALTER TABLE [Member.Members]
ADD [IsActive] BIT NOT NULL DEFAULT 1

ALTER TABLE [Member.Members]
ALTER COLUMN [ZipCode] VARCHAR(20) NULL